# Generated by Django 3.1.3 on 2021-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='r_value',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
