# Generated by Django 3.1.3 on 2021-01-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_auto_20210103_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='r_type',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='r_value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
